import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import About from './components/about';
import ITCMA from "./itcma/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aye Thinzar Aung",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,experience,events,podcast,coversongs,clubcollab,photoshoot,concert,services,mymee,studentCouncil
}: Readonly<{
  children: React.ReactNode;
  experience: React.ReactNode;
  events: React.ReactNode;
  podcast: React.ReactNode;
  coversongs: React.ReactNode;
  clubcollab: React.ReactNode;
  photoshoot:React.ReactNode;
  concert: React.ReactNode;
  services: React.ReactNode;
  mymee: React.ReactNode;
  studentCouncil: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Nav />
        {children}
        <About />
        {experience}
        {events}
        {podcast}
        {coversongs}
        {clubcollab}
        {photoshoot}
        {concert}
        <ITCMA />
        {services}
        {mymee}
        {studentCouncil}
      </body>
    </html>
  );
}
